; AutoHotKey Script Generated by PyWare Automate
F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1
    SetMouseDelay, -1
    SetTitleMatchMode, 
    SendMode, Input
    ; ---- Start of Macro ----
    Sleep, 42
    Send, {F6 up}
    Sleep, 202
    Click, 956, 883
    Sleep, 86
    Click, 956, 883
    Sleep, 113
    Click, 722, 887
    Sleep, 80
    Click, 719, 893
    Sleep, 84
    Click, 859, 947
    Sleep, 135
    Click, 1231, 930
    Sleep, 110
    Click, 1265, 889
    Sleep, 109
    Click, 1151, 849
    Sleep, 70
    Click, 1005, 845
    Sleep, 104
    Click, 922, 901
    Sleep, 85
    Click, 959, 941
    Sleep, 81
    Click, 1089, 948
    Sleep, 162
    Send, {F8 down}
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
; --- PyWare Compatibility Layer ---
StartCaptureThread() {
    return
}

StopCaptureThread() {
    return
}
; ---------------------------------

