; AutoHotKey Script Generated by I Can't Automate

F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1, -1
    SetMouseDelay, -1
    SetDefaultMouseSpeed, 0
    SendMode, Input
    ; ---- Start of Macro ----
Loop, %AmountOfType1% {
	Send, {Enter}
	Sleep, 100
	Send, ^x
	Sleep, 100
	Send, {Up}
	Sleep, 100
	Send, {Right}
	Sleep, 100
	Send, ^v
	Sleep, 100
	Send, {Left}
	Sleep, 100
	; Answer B - scroll 2 times
	Loop, 2 {
		Send, {Enter}
		Sleep, 85
	}
	Send, ^x
	Loop, 2 {
		Send, {Up}
		Sleep, 85
	}
	Loop, 2 {
		Send, {Right}
		Sleep, 85
	}
	Send, ^v
	Loop, 2 {
		Send, {Left}
		Sleep, 85
	}
	; End of answer B
	Loop, 3 {
		Send, {Enter}
		Sleep, 75
	}
	Send, ^x
	Loop, 3 {
		Send, {Up}
		Sleep, 75
	}
	Loop, 3 {
		Send, {Right}
		Sleep, 75
	}
	Send, ^v
	Loop, 3 {
		Send, {Left}
		Sleep, 75
	}
	Loop, 4 {
		Send, {Enter}
		Sleep, 60
	}
	Send, ^x
	Loop, 4 {
		Send, {Up}
		Sleep, 60
	}
	Loop, 4 {
		Send, {Right}
		Sleep, 60
	}
	Send, ^v
	Loop, 4 {
		Send, {Left}
		Sleep, 60
	}
	Loop, 5 {
		Send, {Enter}
		Sleep, 40
	}
	Send, ^x
	Loop, 5 {
		Send, {Up}
		Sleep, 60
	}
	Loop, 5 {
		Send, {Right}
		Sleep, 60
	}
	Send, ^v
	Loop, 5 {
		Send, {Left}
		Sleep, 60
	}
	Loop, 6 {
		Send, {Enter}
		Sleep, 50
	}
	Send, ^x
	Loop, 6 {
		Send, {Up}
		Sleep, 50
	}
	Loop, 6 {
		Send, {Right}
		Sleep, 50
	}
	Send, ^v
	Loop, 6 {
		Send, {Left}
		Sleep, 50
	}
	Sleep, 300
	; Final shop closeout
	Loop, 7 {
		Send, {Enter}
		Sleep, 50
	}
	Sleep, 300
}
Loop, %AmountOfType2% {
	Click, 220, 200
	Sleep, 50
	Send, ^a
	Sleep, 50
	Send, ^c
	Sleep, 50
	Loop, 4 {
		Send, {Enter}
		Sleep, 50
		Click, 220, 200
		Sleep, 50
		Send, ^v
		Sleep, 50
		Send, {Right}
		Sleep, 50
		; Reset alignment if possible
		Send, {Enter}
		Sleep, 50
		Send, {Up}
		Sleep, 50
		Loop, 10 {
			Send, {Left}
			Sleep, 50
		}
		Send, {Right}
		Sleep, 50
		Send, {Right}
		Sleep, 50
		; VIETNAMESE OR ENGLISH
		if (VietnameseMode == 1) {
			Send, A. Đúng
			Sleep, 50
			Send, {Right}
			Sleep, 50
			Send, B. Sai
			Sleep, 50
		} else {
			Send, A. True
			Sleep, 50
			Send, {Right}
			Sleep, 50
			Send, B. False
			Sleep, 50
		}
		Sleep, 100
		Send, {Left}
		Sleep, 50
		Send, {Left}
		Sleep, 200
	}
	Send, {Enter}
	Sleep, 50
	Send, ^x
	Loop, 4 {
		Send, {Up}
		Sleep, 50
		Send, {Right}
		Sleep, 50
	}
	Sleep, 50
	Send, {Right}
	Sleep, 50
	Send, ^v
	Sleep, 50
	Send, {Left}
	Sleep, 50
	Loop, 4 {
		Send, {Enter}
		Sleep, 50
		Send, {Left}
		Sleep, 50
	}
	Send, {Enter}
	Sleep, 50
	Send, {Shift Enter}
	Loop, 3 {
		Sleep, 50
		Send, {Enter}
	}
	Send, {Shift up}
	Send, ^x
	Loop, 5 {
		Send, {Up}
		Sleep, 50
		Send, {Right}
		Sleep, 50
	}
	Sleep, 50
	Send, {Right}
	Sleep, 50
	Send, ^v
	Sleep, 50
	Send, {Left}
	Sleep, 50
	Send, ^c
	Loop, 3 {
		Sleep, 50
		Send, {Enter}
		Send, ^v
	}
	Loop, 5 {
		Send, {Left}
		Sleep, 50
		Send, {Enter}
		Sleep, 50
	}
	Sleep, 50
	Send, {Enter}
}
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
