; AutoHotKey Script Generated by I Can't Automate
Z:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1, -1
    SetMouseDelay, -1
    SetDefaultMouseSpeed, 0
    SendMode, Input
    ; ---- Start of Macro ----
    Send, {Shift down}
    Send, {* down}
    Send, {* up}
    Send, {* down}
    Send, {* up}
    Send, {Shift up}
    Send, {Right}
    Send, {Shift down}
    Send, {* down}
    Send, {* up}
    Send, {* down}
    Send, {* up}
    Send, {Shift up}
    ; ---- End of Macro ----
return

M::
    ExitApp
return
