; AutoHotKey Script Generated by PyWare Automate
F5:: ; Start macro
    SetBatchLines, -1
    SetKeyDelay, -1
    SetMouseDelay, -1
    SetTitleMatchMode, 2
    SendMode, Input
    ; ---- Start of Macro ----
	PixelSearch, FoundX, FoundY, 547, 866, 1373, 910, 0x5B4B43, 5, Fast
	MsgBox, 1, %ErrorLevel%
    ; ---- End of Macro ----
return

F7::
    ExitApp
return
; --- PyWare Compatibility Layer ---
StartCaptureThread() {
    return
}

StopCaptureThread() {
    return
}
; ---------------------------------

